### ISSUE TITLE
Issue running it Github Actions using ubuntu-latest

### ISSUE THREAD

**Issue by mrz1836** [tryvium-travels/memongo#25]
Hi ya'll!

We are receiving this error from Github Actions when using the new version `v0.8.0`:
```
[memongo] [INFO]  Starting MongoDB with options &memongo.Options{ShouldUseReplica:false, Port:32841, CachePath:"/home/runner/.cache/memongo", MongoVersion:"4.2.1", DownloadURL:"https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-4.2.1.tgz", MongodBin:"", Logger:(*log.Logger)(nil), LogLevel:0, StartupTimeout:10000000000, Auth:false}
[memongo] [INFO]  mongod from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-4.2.1.tgz does not exist in cache, downloading to /home/runner/.cache/memongo/mongodb-linux-x86_64-ubuntu2204-4_2_1_tgz_9ce45a6aea/mongod
--- FAIL: TestCreateMongoServer (0.23s)
    --- FAIL: TestCreateMongoServer/valid_server (0.23s)
        embedded_test.go:31: 
            	Error Trace:	/home/runner/work/bux/bux/tester/embedded_test.go:31
            	Error:      	Received unexpected error:
            	            	error intializing gzip reader from /tmp/430061428: gzip: invalid header
            	Test:       	TestCreateMongoServer/valid_server
FAIL
```

We do not get the same error when using `v0.6.1` however.

Here is the section in our Github actions file:
```
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3 
   .......
   .......
```

You can see we are using the latest version of Ubuntu, but we are still getting an error with loading memongo.

We also referenced: #9 but again, using ubuntu-latest is not working.

Also, the error message has a spelling error: `error intializing gzip` vs `error initializing gzip`

**Comment by mrz1836** [comment]
Also same issue when trying to use `5.0.0`

```
[memongo] [INFO]  Starting MongoDB with options &memongo.Options{ShouldUseReplica:false, Port:43633, CachePath:"/home/runner/.cache/memongo", MongoVersion:"5.0.0", DownloadURL:"https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-5.0.0.tgz", MongodBin:"", Logger:(*log.Logger)(nil), LogLevel:0, StartupTimeout:10000000000, Auth:false}
[memongo] [INFO]  mongod from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-5.0.0.tgz does not exist in cache, downloading to /home/runner/.cache/memongo/mongodb-linux-x86_64-ubuntu2204-5_0_0_tgz_61615ecd00/mongod
--- FAIL: TestCreateMongoServer (0.47s)
    --- FAIL: TestCreateMongoServer/valid_server (0.47s)
        embedded_test.go:32: 
            	Error Trace:	/home/runner/work/bux/bux/tester/embedded_test.go:32
            	Error:      	Received unexpected error:
            	            	error intializing gzip reader from /tmp/606116749: gzip: invalid header
            	Test:       	TestCreateMongoServer/valid_server
FAIL
```

**Comment by saniales** [comment]
solved with new version v0.9.0

**Comment by mrz1836** [comment]
Thanks @saniales - however I am still getting the same error.

Updated the package:
<img width="629" alt="Screenshot 2023-02-02 at 9 28 10 AM" src="https://user-images.githubusercontent.com/3743002/216351911-4a0f7619-e242-454d-ba43-7daeaaf7491a.png">


Getting this error:
<img width="1340" alt="Screenshot 2023-02-02 at 9 27 35 AM" src="https://user-images.githubusercontent.com/3743002/216351950-0082f3dd-f3ef-4297-bbbf-473dc11ac02a.png">

**Comment by saniales** [comment]
You can check on mongodb download page which 5 version you can download, please double check and let me know

**Comment by mrz1836** [comment]
Thanks @saniales - I did not know there was a more current version. I updated it from `5.0.0` to the latest stable release for `v5` to the version `5.0.14` but still getting the same error.

<img width="1325" alt="Screenshot 2023-02-02 at 9 39 30 AM" src="https://user-images.githubusercontent.com/3743002/216354701-e3309655-2dc1-4bdb-ae2e-585e431e3c57.png">

**Comment by mrz1836** [comment]
Should I just skip the `v5` entirely and use `v6`?

**Comment by mrz1836** [comment]
Really strange @saniales, GitHub fails at downloading that file, yet when I navigate to the file in the browser it downloads fine.

Download Link: `https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-5.0.14.tgz`

Here is taking the url and trying to open in a browser:

<img width="773" alt="Screenshot 2023-02-02 at 9 47 28 AM" src="https://user-images.githubusercontent.com/3743002/216356591-b3197d8a-39ff-44a4-9760-2171911f3985.png">

**Comment by mrz1836** [comment]
Changing the version is resulting in the same error: `error intializing gzip reader from /tmp/476466906: gzip: invalid header, https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.4.tgz`

**Comment by saniales** [comment]
Can you try to clean runner cache and run again the action? I had a similar problem and this solved

**Comment by mrz1836** [comment]
I don't see any cache to remove - am I missing something?

<img width="1102" alt="Screenshot 2023-02-02 at 9 53 32 AM" src="https://user-images.githubusercontent.com/3743002/216358098-1422c9b3-83ab-42fa-8104-cef1a8d254c6.png">

**Comment by mrz1836** [comment]
I changed the `Go` cache key just to ensure nothing was being cached... Got the same result @saniales 

<img width="550" alt="Screenshot 2023-02-02 at 9 59 33 AM" src="https://user-images.githubusercontent.com/3743002/216359885-1ca611f0-c37b-4c45-918f-5110f25e9a69.png">

<img width="1309" alt="Screenshot 2023-02-02 at 10 00 11 AM" src="https://user-images.githubusercontent.com/3743002/216359986-60e06532-9d78-4ca1-b40b-87767e85d1d2.png">

**Comment by saniales** [comment]
If you open the url it downloads?

**Comment by mrz1836** [comment]
Yes and no, if I open it in a browser it gives me this error:

<img width="773" alt="Screenshot 2023-02-02 at 9 47 28 AM" src="https://user-images.githubusercontent.com/3743002/216356591-b3197d8a-39ff-44a4-9760-2171911f3985.png">

If I click the download link (not navigating to the url) it downloads

**Comment by saniales** [comment]
There is no version 5.0.14 of mongo on download section for ubuntu 22

![image](https://user-images.githubusercontent.com/3513298/216372936-29127696-ee3e-438c-aa18-8ac885f68b7c.png)

Probably that is the reason

try downloading 6.0.4 (which works on my machine ubuntu-2204 on WSL, plus also in my pipelines in github actions) or use the ubuntu 2004 runner, as mongo 5 is not supported on ubuntu 2204

**Comment by mrz1836** [comment]
Wow looks like it now worked for `v6.0.4`

Sorry @saniales for all the back and forth - but looks like it is now resolved!
